import React from "react";
import {
  Building2,
  Home,
  LogOut,
  UserPlus,
  RefreshCw,
  Search,
  Filter,
  Download,
  Edit,
  Trash2,
  Check,
  X,
  CalendarX,
  Calendar,
  Clock,
  Building,
  Star,
  Plus,
  Edit2,
  Upload,
  FileText,
  AlertTriangle,
  AlertCircle,
  XCircle,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronUp,
  User,
  Users,
  Mail,
  Phone,
  MapPin,
  DollarSign,
  Briefcase,
  Shield,
  Settings,
  Eye,
  EyeOff,
  Save,
  Loader,
  Menu,
  MoreVertical,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Info,
  UserCheck,
  Timer,
  CalendarCheck,
  CalendarDays,
  MessageCircle,
  Send,
  SearchX,
  CheckCircle2,
} from "lucide-react";

// Icon name to component mapping
const iconMap = {
  "building-2": Building2,
  home: Home,
  "log-out": LogOut,
  "user-plus": UserPlus,
  "refresh-cw": RefreshCw,
  search: Search,
  filter: Filter,
  download: Download,
  edit: Edit,
  "trash-2": Trash2,
  check: Check,
  x: X,
  "calendar-x": CalendarX,
  calendar: Calendar,
  clock: Clock,
  building: Building,
  star: Star,
  plus: Plus,
  "edit-2": Edit2,
  upload: Upload,
  "file-text": FileText,
  "alert-triangle": AlertTriangle,
  "alert-circle": AlertCircle,
  "x-circle": XCircle,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  user: User,
  users: Users,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  "dollar-sign": DollarSign,
  briefcase: Briefcase,
  shield: Shield,
  settings: Settings,
  eye: Eye,
  "eye-off": EyeOff,
  save: Save,
  loader: Loader,
  menu: Menu,
  "more-vertical": MoreVertical,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  lock: Lock,
  info: Info,
  "user-check": UserCheck,
  timer: Timer,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "message-circle": MessageCircle,
  send: Send,
  "search-x": SearchX,
  "check-circle-2": CheckCircle2,
};

const Icon = ({ name, className = "", size = 16, ...props }) => {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found in iconMap`);
    return null;
  }

  return <IconComponent className={className} size={size} {...props} />;
};

export default Icon;
